server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/employee
    username: root
    password: Cjs414ghqja!

  profiles:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
          format_sql: true
          use_sql_comments: true
          hbm2ddl:
            import_files: import.sql
  jpa:
    hibernate:
      ddl-auto: update

